language: node_js
node_js: "node"
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - npm run build
  - npm run distribution
after_success:
  - npm run report-coverage
git:
  depth: 3